# https://github.com/anothrNick/github-tag-action
# example 2: on merge to master from pull request (recommended)
name: Deploy to Azure
on:
  pull_request:
    types:
      - closed
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  DOTNET_VERSION: '7.0.x'
  SOURCE_FILE_LOCATION: Stocks.sln

jobs:
  tagVersion:
    name: Tag version
    if: github.event.pull_request.merged || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.merge_commit_sha }}
        fetch-depth: '0'
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.64.0 # Don't use @master or @v1 unless you're happy to test the latest version
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # if you don't want to set write permissions use a PAT token
        WITH_V: true
  build:
    needs: tagVersion
    name: Deploy to Azure
    if: github.event.pull_request.merged || github.event_name == 'workflow_dispatch'
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Check out branch
        uses: actions/checkout@main      
      - name: Setup .NET Core ${{ env.DOTNET_VERSION }} 
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Dotnet build and publish
        run: |
          dotnet restore
          dotnet build --configuration Release
          dotnet publish -c Release -o '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp'
      - name: App Settings Variable Substitution
        uses: microsoft/variable-substitution@v1
        with:
            files: '${{env.AZURE_WEBAPP_PACKAGE_PATH}}/myapp/appsettings.json'
        env:
           ConnectionStrings.Redis: ${{ secrets.REDIS_CONNECTION }} 
           ConnectionStrings.StockWebDividendDB: ${{ secrets.STOCKWEBDIVIDENDDB_CONNECTION }}
      - name: 'Run Azure webapp deploy action using publish profile credentials'
        uses: azure/webapps-deploy@v2
        with: 
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }} 
          package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp'
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2   
        with:
          path: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp'

