name: Run tests
on:
  push:
    branches:
      - '*'
      - '!main'

env:
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  DOTNET_VERSION: '7.0.x'
  SOURCE_FILE_LOCATION: Stocks.sln

jobs:
  build:
    name: Run tests
    runs-on: windows-latest
    steps:
      - name: Check out branch
        uses: actions/checkout@main      
      - name: Setup .NET Core ${{ env.DOTNET_VERSION }} 
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Run tests
        run: dotnet test --no-restore --verbosity normal $sourcefilelocation
      - name: Logging tests
        run: dotnet test --logger trx --results-directory "testresults-${{ env.DOTNET_VERSION }}" $SOURCE_FILE_LOCATION
      - name: Upload dotnet test results
        uses: actions/upload-artifact@v3
        with:
          name: dotnet-results-${{ env.DOTNET_VERSION }}
          path: TestResults-${{ env.DOTNET_VERSION }}
        if: ${{ always() }}