on:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: StockDividend    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '7.0.x'           # set this to the dot net version to use
  SOURCE_FILE_LOCATION: Stocks.sln

jobs:
  build:
    name: .NET Core CI
    runs-on: windows-latest

    steps:
      - name: Check out branch
        uses: actions/checkout@main
      
      - name: Setup .NET Core ${{ env.DOTNET_VERSION }} 
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }} 
      
      - name: Dotnet build and publish
        run: |
          dotnet restore
          dotnet build --configuration Release
          dotnet publish -c Release --no-restore $sourceFileLocation --property:PublishDir='${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp' 
          
      - name: 'Run Azure webapp deploy action using publish profile credentials'
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }} 
          package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp'
