# https://github.com/anothrNick/github-tag-action
# example 2: on merge to master from pull request (recommended)
name: Deploy to Azure
on:
  pull_request:
    types:
      - closed
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  DOTNET_VERSION: '7.0.x'
  SOURCE_FILE_LOCATION: Stocks.sln

jobs:
  deploy:
    name: Deploy to Azure
    runs-on:  windows-latest
    if: github.event.pull_request.merged || github.event_name == 'workflow_dispatch'
    steps:
      - name: Check out branch
        uses: actions/checkout@main      
      - name: Setup .NET Core ${{ env.DOTNET_VERSION }} 
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Dotnet build and publish
        run: |
          dotnet restore
          dotnet build --configuration Release
          dotnet publish -c Release -o '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp' 
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2         
#        - name: App Settings Variable Substitution
#          uses: microsoft/variable-substitution@v1
#          with:
#            files: '${{env.AZURE_WEBAPP_PACKAGE_PATH}}/myapp/appsettings.json'
#          env:
#            ConnectionStrings.Default: ${{ secrets.SOME_CONNECTION_STRING }}
#            App.ServerRootAddress: ${{ env.SERVER_ROOT_ADDRESS }}
